from datetime import datetime
from app import db
from app.herpers.utilis import BaseModel

class Contract(db.Model, BaseModel):
    __bind_key__            = 'OTLC'
    __tablename__           = 'TCCONTRATOS'
    CN_EMP                  = db.Column(db.String(12))  
    CN_PLAN                 = db.Column(db.String(1))
    CN_CONTRATO             = db.Column(db.String(20), primary_key=True)  
    CN_TIPO_CONTRATO        = db.Column(db.String(14))  
    CN_CATEGORIA            = db.Column(db.String(12))  
    CN_NOMBRE               = db.Column(db.String(50))  
    CN_APELLIDO             = db.Column(db.String(50))  
    CN_FECHA_NAC            = db.Column(db.DateTime())  
    CN_RFC                  = db.Column(db.String(15))  
    CN_NACIONALIDAD         = db.Column(db.String(20))  
    CN_GENERO               = db.Column(db.String(3))  
    CN_IDIOMA               = db.Column(db.String(20))  
    CN_LADA                 = db.Column(db.String(3))  
    CN_TELEFONO             = db.Column(db.String(20))  
    CN_EMAIL                = db.Column(db.String(100)) 
    CN_PRECIO_VENTA         = db.Column(db.Numeric(12,2))  
    CN_PLAZO                = db.Column(db.Numeric(3))  
    CN_TASA_INTERES         = db.Column(db.Numeric(5,2))  
    CN_INTERES_TOTAL        = db.Column(db.Numeric(12,2))  
    CN_ENGANCHE_POR         = db.Column(db.Numeric(5,2))  
    CN_ENGANCHE_IMP         = db.Column(db.Numeric(12,2))  
    CN_ENGANCHE_FECHA       = db.Column(db.DateTime())  
    CN_MENSUALIDAD          = db.Column(db.Numeric(12,2))  
    CN_SALDO_FINANCIADO     = db.Column(db.Numeric(12,2))  
    CN_COSTO_CONTRATO       = db.Column(db.Numeric(12,2))  
    CN_STATUS_PAGOS         = db.Column(db.String(12))  
    CN_STATUS_CONTRATO      = db.Column(db.String(12))  
    CN_CAP_U                = db.Column(db.String(12))  
    CN_CAP_F                = db.Column(db.DateTime())  
    CN_CAP_H                = db.Column(db.String(5))  
    CN_MONEDA               = db.Column(db.String(3))  
    CN_TC                   = db.Column(db.Numeric(9,4))  
    CN_NOMBRE_COP           = db.Column(db.String(50))  
    CN_APELLIDO_COP         = db.Column(db.String(50))  
    CN_CAPITAL_TOTAL        = db.Column(db.Numeric(12,2))  
    CN_TEL_TRABAJO          = db.Column(db.String(15))  
    CN_TEL_CELULAR          = db.Column(db.String(30))  
    CN_PRIMER_PAGO          = db.Column(db.DateTime())  
    CN_CC_FPAGO             = db.Column(db.String(20))  
    CN_CC_MONEDA            = db.Column(db.String(3))  
    CN_CC_FECHA             = db.Column(db.DateTime())  
    CN_CC_REFERENCIA        = db.Column(db.String(20))  
    CN_CC_AUTORIZACION      = db.Column(db.String(50))  
    CN_CC_CAP_U             = db.Column(db.String(12))  
    CN_ENG_FPAGO            = db.Column(db.String(20))  
    CN_ENG_MONEDA           = db.Column(db.String(3))  
    CN_ENG_FECHA            = db.Column(db.DateTime())  
    CN_ENG_REFERENCIA       = db.Column(db.String(20))  
    CN_ENG_AUTORIZACION     = db.Column(db.String(50))  
    CN_ENG_CAP_U            = db.Column(db.String(12))  
    CN_MEMBRESIA            = db.Column(db.Numeric(12,2))  
    CN_SEMANAS_PAQ          = db.Column(db.Numeric(12,2))  
    CN_REGALOS              = db.Column(db.Numeric(12,2))
    CN_CC_PAGO              = db.Column(db.Numeric(12,2))
    CN_ENG_PAGO             = db.Column(db.Numeric(12,2))
    CN_BENEFICIARIOS        = db.Column(db.String(300))
    CN_DIRECCION            = db.Column(db.String(100))
    CN_CIUDAD               = db.Column(db.String(100))
    CN_ESTADO               = db.Column(db.String(100))
    CN_NOCHES_INTERCAMBIO   = db.Column(db.Numeric(3))
    CN_PROVISIONES          = db.Column(db.Numeric(12,2))
    CN_SALA                 = db.Column(db.String(30))
    CN_MOD_F                = db.Column(db.DateTime, default=datetime.now())
    CN_VENTA_F              = db.Column(db.DateTime)
    CN_PROC_F               = db.Column(db.DateTime)
    CN_CAN_F                = db.Column(db.DateTime)

    def to_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}

class Movement(db.Model, BaseModel):
    __bind_key__        = 'OTLC'
    __tablename__       = 'TCMOVIM'
    MO_EMP              = db.Column(db.String(12), nullable=False, primary_key=True)
    MO_PLAN             = db.Column(db.String(1), nullable=False, primary_key=True)
    MO_CONTRATO         = db.Column(db.String(20), nullable=False, primary_key=True)
    MO_PAGO             = db.Column(db.Numeric(12,2), nullable=False, primary_key=True)
    MO_FECHA            = db.Column(db.DateTime(), nullable=False)
    MO_DOCUMENTO        = db.Column(db.String(12), nullable=False)
    MO_TIPOMOV          = db.Column(db.String(20), nullable=False)
    MO_FORMA_PAGO       = db.Column(db.String(12), nullable=False)
    MO_MONEDA           = db.Column(db.String(3), nullable=False)
    MO_TC               = db.Column(db.Numeric(9,4), nullable=False)
    MO_CAPITAL          = db.Column(db.Numeric(12,2), nullable=False)
    MO_INTERES          = db.Column(db.Numeric(12,2), nullable=False)
    MO_TOTAL            = db.Column(db.Numeric(12,2), nullable=False)
    MO_TARJETA          = db.Column(db.String(16), nullable=False)
    MO_COMPROBANTE      = db.Column(db.String(12), nullable=True)
    MO_AUTORIZACION     = db.Column(db.String(12), nullable=False)
    MO_MOTIVO           = db.Column(db.String(200), nullable=True)
    MO_REFERENCIA       = db.Column(db.String(50), nullable=False)
    MO_STATUS           = db.Column(db.String(12), nullable=False)
    MO_NOTAS_USUARIO    = db.Column(db.String(50), nullable=True)
    MO_NOTAS_SISTEMA    = db.Column(db.String(50), nullable=True)
    MO_CONTA_EJE        = db.Column(db.String(2), nullable=True)
    MO_CONTA_PER        = db.Column(db.String(2), nullable=True)
    MO_CONTA_ASIENTO    = db.Column(db.String(12), nullable=True)
    MO_REFINA           = db.Column(db.String(12), nullable=True)
    MO_MONTO            = db.Column(db.Numeric(12,2), nullable=False)
    MO_MONTO_ID         = db.Column(db.Numeric(12), nullable=False)
    MO_CAP_U            = db.Column(db.String(12), nullable=False)
    MO_CAP_F            = db.Column(db.DateTime(), nullable=False)
    MO_CAP_H            = db.Column(db.String(5), nullable=False)
    MO_CAN_TOT          = db.Column(db.Numeric(12,2), nullable=True)

    def to_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}

class AccountStatusHeader(db.Model, BaseModel):
    __bind_key__        = 'OTLC'
    __tablename__       = 'TCEDOCTAETMP'
    EE_SESION           = db.Column(db.String(12), nullable=False)
    EE_FECHA_GEN        = db.Column(db.DateTime(), nullable=False, info={'name':'Fecha'})
    EE_USUARIO          = db.Column(db.String(12), nullable=False, info={'name':'Usuario'})
    EE_CONTRATO         = db.Column(db.String(20), nullable=False, info={'name':'Contrato'}, primary_key=True)
    EE_SOCIO1           = db.Column(db.String(100), nullable=False, info={'name':'Socio1'})
    EE_SOCIO2           = db.Column(db.String(100), nullable=False, info={'name':'Socio2'})
    EE_TIPO             = db.Column(db.String(30), nullable=False)
    EE_PRECIO           = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Precio Contrato'})
    EE_PAGO_MENSUAL     = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Pago Mensual'})
    EE_MONEDA           = db.Column(db.String(3), nullable=False, info={'name':'Moneda'})
    EE_PM_INICIAL       = db.Column(db.Numeric(3,0), nullable=False, info={'name':'Plazo Inicial'})
    EE_PM_PAGADO        = db.Column(db.Numeric(3,0), nullable=False, info={'name':'Plazo Pagado'})
    EE_PM_SALDO         = db.Column(db.Numeric(3,0), nullable=False, info={'name':'Plazo Saldo'})
    EE_CC_INICIAL       = db.Column(db.Numeric(3,0), nullable=False, info={'name':'Costo Contrato Inicial'})
    EE_CC_PAGADO        = db.Column(db.Numeric(3,0), nullable=False, info={'name':'Costo Contrato Pagado'})
    EE_CC_SALDO         = db.Column(db.Numeric(3,0), nullable=False, info={'name':'Costo Contrato Saldo'})
    EE_EG_POR           = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Enganche Por'})
    EE_EG_IMP           = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Enganche Inicial'})
    EE_EG_PAGADO        = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Enganche Pagado'})
    EE_EG_SALDO         = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Enganche Saldo'})
    EE_FN_INICIAL       = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Financiamiento Inicial'})
    EE_FN_PAGADO        = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Financiamiento Pagado'})
    EE_FN_SALDO         = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Financiamiento Saldo'})
    EE_IN_INICIAL       = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Interes Inicial'})
    EE_IN_PAGADO        = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Interes Pagado'})
    EE_IN_SALDO         = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Interes Saldo'})
    EE_MT_INICIAL       = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Total Inicial'})
    EE_MT_PAGADO        = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Total Pagado'})
    EE_MT_SALDO         = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Total Saldo'})
    EE_TASA_INTERES     = db.Column(db.Numeric(7,2), nullable=True, info={'name':'Tasa Interes'})
    EE_TC               = db.Column(db.Numeric(9,4), info={'name':'TC'})

    def to_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}

class AccountStatusBody(db.Model, BaseModel):
    __bind_key__     = 'OTLC'
    __tablename__    = 'TCEDOCTADTMP'
    ED_SESION        = db.Column(db.String(12), nullable=False)
    ED_FECHA_GEN     = db.Column(db.DateTime(), nullable=False)
    ED_USUARIO       = db.Column(db.String(12), nullable=False)
    ED_CONTRATO      = db.Column(db.String(20), nullable=False)
    ED_SECUENCIA     = db.Column(db.Numeric(6,0), nullable=False, primary_key=True)
    ED_PERIODO       = db.Column(db.String(3), nullable=False, info={'name':'Pago'})
    ED_VENCIMIENTO   = db.Column(db.DateTime(), nullable=False, info={'name':'Vencimiento'})
    ED_CAPITAL       = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Capital'})
    ED_INTERES       = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Interes'})
    ED_TOTAL         = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Total'})
    ED_FECHA_PAGO    = db.Column(db.DateTime(), nullable=False, info={'name':'Fecha Pago'})
    ED_TOTAL_PAGADO  = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Total Pagado'})
    ED_TOTAL_SALDO   = db.Column(db.Numeric(12,2), nullable=False, info={'name':'Saldo Mes'})
    ED_FORMA_PAGO    = db.Column(db.String(12), nullable=False, info={'name':'Forma Pago'})
    ED_REFERENCIA    = db.Column(db.String(20), nullable=False, info={'name':'Referencia'})
    ED_CONCEPTO      = db.Column(db.String(12), nullable=False, info={'name':'Concepto'})
    ED_FORMATO       = db.Column(db.String(20), nullable=False)

    def to_dict(self):
       return {c.name: getattr(self, c.name) for c in self.__table__.columns}